import type { LabelValueProps } from "@/types/common";

export const LANGUAGE_OPTIONS: LabelValueProps[] = [
  { label: "English", value: "English" },
  { label: "Mandarin Chinese", value: "Mandarin Chinese" },
  { label: "Spanish", value: "Spanish" },
  { label: "Hindi", value: "Hindi" },
  { label: "Arabic", value: "Arabic" },
  { label: "Bengali", value: "Bengali" },
  { label: "Portuguese", value: "Portuguese" },
  { label: "Russian", value: "Russian" },
  { label: "Japanese", value: "Japanese" },
  { label: "German", value: "German" },
  { label: "French", value: "French" },
  { label: "Korean", value: "Korean" },
  { label: "Vietnamese", value: "Vietnamese" },
  { label: "Thai", value: "Thai" },
  { label: "Indonesian", value: "Indonesian" },
  { label: "Malay", value: "Malay" },
  { label: "Tagalog", value: "Tagalog" },
  { label: "Burmese", value: "Burmese" },
  { label: "Khmer", value: "Khmer" },
  { label: "Lao", value: "Lao" },
  { label: "Mongolian", value: "Mongolian" },
  { label: "Cantonese", value: "Cantonese" },
  { label: "Taiwanese", value: "Taiwanese" },
  { label: "Urdu", value: "Urdu" },
  { label: "Tamil", value: "Tamil" },
  { label: "Telugu", value: "Telugu" },
  { label: "Marathi", value: "Marathi" },
  { label: "Gujarati", value: "Gujarati" },
  { label: "Kannada", value: "Kannada" },
  { label: "Malayalam", value: "Malayalam" },
  { label: "Punjabi", value: "Punjabi" },
  { label: "Nepali", value: "Nepali" },
  { label: "Sinhala", value: "Sinhala" },
  { label: "Hebrew", value: "Hebrew" },
  { label: "Persian (Farsi)", value: "Persian (Farsi)" },
  { label: "Kurdish", value: "Kurdish" },
  { label: "Pashto", value: "Pashto" },
  { label: "Dari", value: "Dari" },
  { label: "Italian", value: "Italian" },
  { label: "Dutch", value: "Dutch" },
  { label: "Polish", value: "Polish" },
  { label: "Ukrainian", value: "Ukrainian" },
  { label: "Greek", value: "Greek" },
  { label: "Czech", value: "Czech" },
  { label: "Hungarian", value: "Hungarian" },
  { label: "Swedish", value: "Swedish" },
  { label: "Danish", value: "Danish" },
  { label: "Finnish", value: "Finnish" },
  { label: "Norwegian", value: "Norwegian" },
  { label: "Romanian", value: "Romanian" },
  { label: "Bulgarian", value: "Bulgarian" },
  { label: "Serbian", value: "Serbian" },
  { label: "Croatian", value: "Croatian" },
  { label: "Slovak", value: "Slovak" },
  { label: "Slovenian", value: "Slovenian" },
  { label: "Lithuanian", value: "Lithuanian" },
  { label: "Latvian", value: "Latvian" },
  { label: "Estonian", value: "Estonian" },
  { label: "Icelandic", value: "Icelandic" },
  { label: "Irish", value: "Irish" },
  { label: "Welsh", value: "Welsh" },
  { label: "Scottish Gaelic", value: "Scottish Gaelic" },
  { label: "Catalan", value: "Catalan" },
  { label: "Basque", value: "Basque" },
  { label: "Galician", value: "Galician" },
  { label: "Swahili", value: "Swahili" },
  { label: "Amharic", value: "Amharic" },
  { label: "Hausa", value: "Hausa" },
  { label: "Yoruba", value: "Yoruba" },
  { label: "Igbo", value: "Igbo" },
  { label: "Zulu", value: "Zulu" },
  { label: "Afrikaans", value: "Afrikaans" },
  { label: "Xhosa", value: "Xhosa" },
  { label: "Somali", value: "Somali" },
  { label: "Kazakh", value: "Kazakh" },
  { label: "Uzbek", value: "Uzbek" },
  { label: "Azerbaijani", value: "Azerbaijani" },
  { label: "Georgian", value: "Georgian" },
  { label: "Armenian", value: "Armenian" },
  { label: "Kyrgyz", value: "Kyrgyz" },
  { label: "Turkmen", value: "Turkmen" },
  { label: "Tajik", value: "Tajik" },
  { label: "Maori", value: "Maori" },
  { label: "Samoan", value: "Samoan" },
  { label: "Hawaiian", value: "Hawaiian" },
  { label: "Fijian", value: "Fijian" },
  { label: "Latin", value: "Latin" },
  { label: "Sanskrit", value: "Sanskrit" },
  { label: "Esperanto", value: "Esperanto" },
];

export const PROFICIENCY_OPTIONS: LabelValueProps[] = [
  { label: "Native", value: "Native" },
  { label: "Fluent", value: "Fluent" },
  { label: "Advanced", value: "Advanced" },
  { label: "Intermediate", value: "Intermediate" },
  { label: "Beginner", value: "Beginner" },
];

export const EMPLOYMENT_TYPE_OPTIONS: LabelValueProps[] = [
  { label: "Full-time", value: "Full-time" },
  { label: "Part-time", value: "Part-time" },
  { label: "Contract", value: "Contract" },
  { label: "Freelance", value: "Freelance" },
  { label: "Internship", value: "Internship" },
  { label: "Remote", value: "Remote" },
];

export const MONTH_OPTIONS: LabelValueProps[] = [
  { label: "January", value: "January" },
  { label: "February", value: "February" },
  { label: "March", value: "March" },
  { label: "April", value: "April" },
  { label: "May", value: "May" },
  { label: "June", value: "June" },
  { label: "July", value: "July" },
  { label: "August", value: "August" },
  { label: "September", value: "September" },
  { label: "October", value: "October" },
  { label: "November", value: "November" },
  { label: "December", value: "December" },
];

export const DEGREE_OPTIONS: LabelValueProps[] = [
  { label: "High School Diploma", value: "High School Diploma" },
  { label: "Associate's", value: "Associate's" },
  { label: "Bachelor's", value: "Bachelor's" },
  { label: "Master's", value: "Master's" },
  { label: "Doctorate (PhD)", value: "Doctorate (PhD)" },
  { label: "Professional (MD, JD, etc.)", value: "Professional" },
  { label: "Certificate", value: "Certificate" },
  { label: "Bootcamp", value: "Bootcamp" },
  { label: "Other", value: "Other" },
];
